pipeline:
  build-docker-linux:
    image: docker
    commands:
      - docker build --rm -t switch-lan-play-build:linux -f docker/Dockerfile.linux .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  build-docker-win:
    image: docker
    commands:
      - docker build --rm -t switch-lan-play-build:win -f docker/Dockerfile.win .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  lan-play-linux:
    group: build
    image: switch-lan-play-build:linux
    commands:
      - mkdir build.linux && cd build.linux
      - cmake ..
      - make -j$$(nproc)
  lan-play-windows:
    group: build
    image: switch-lan-play-build:win
    commands:
      - mkdir build.win && cd build.win
      - cmake -DCMAKE_TOOLCHAIN_FILE=../cmake/toolchain-mingw32.cmake ..
      - make -j$$(nproc)
  server:
    group: build
    image: node:alpine
    commands:
      - cd server
      - npm install
      - npm run build
  github_pre_release:
    image: plugins/github-release
    secrets: [ github_token ]
    files:
      - build.linux/lan-play
      - build.win/lan-play.exe
    checksum:
       - sha1
    prerelease: true
    when:
      event: tag
